# Generated by Django 4.2.16 on 2026-03-01 05:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='Минимум 10 символов', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Комментарий')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Если True, автор не показывается получателю', verbose_name='Анонимный отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Например: Высокая экспертность', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Уникальный идентификатор (генерируется автоматически)', max_length=100, unique=True, verbose_name='Slug')),
                ('sentiment', models.CharField(choices=[('positive', 'Позитивный'), ('negative', 'Негативный')], db_index=True, max_length=20, verbose_name='Тональность')),
                ('icon', models.CharField(default='👍', help_text='Emoji или название иконки Ant Design', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, default='', help_text='Подсказка для пользователя при выборе тега', verbose_name='Описание')),
                ('color', models.CharField(default='#1890ff', help_text='HEX цвет для отображения, например: #4CAF50', max_length=7, verbose_name='Цвет')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['sentiment', 'sort_order', 'name'],
            },
        ),
    ]
