# Generated by Django 4.2.16 on 2026-03-01 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tags',
            field=models.ManyToManyField(related_name='feedbacks', to='feedback.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['author', 'created_at'], name='feedback_fe_author__990854_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['recipient', 'created_at'], name='feedback_fe_recipie_0cee80_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['task', 'created_at'], name='feedback_fe_task_id_567242_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('author', 'recipient', 'task'), name='unique_feedback_per_task'),
        ),
    ]
